name: Run_main.go_and_Push_Generated_File

on:
  schedule:
    - cron: '*/20 * * * *'  # 每 20 分钟触发一次
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 根据你的 Go 版本调整

      - name: Run main.go
        run: |
          go run main.go

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Force Add and Commit file  # 强制添加并提交 adblock_geosite.dat 文件
        run: |
          git add -f adblock_geosite.dat  # 强制添加 adblock_geosite.dat 文件到根目录
          git commit -m 'Update adblock_geosite.dat' || echo "No changes to commit"

      - name: Push changes to repository  # 推送更改到远程仓库
        env:
          TOKEN: ${{ secrets.TOKEN }}  # 使用 GitHub 密钥进行身份验证
        run: |
          git push --force "https://${TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
