name: Run_Go_Program_and_Push_Changes

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: '*/20 * * * *' # 每20分钟运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # 指定Go版本

    - name: Create go.mod
      run: |
        go mod init example.com/myapp || echo "go.mod already exists"

    - name: Add dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run Go program
      run: go run main.go

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit and push changes
      run: |
        git add geosite.dat
        git diff --cached --quiet || (git commit -m "Update geosite.dat" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
