name: Run_main.go_and_Push_Generated_File

on:
  schedule:
    - cron: '*/20 * * * *'  # 每 20 分钟触发一次
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 根据你的 Go 版本调整

      - name: Set up Go Module
        run: |
          mkdir -p mymodule
          mv main.go mymodule/
          cd mymodule
          go mod init example.com/mymodule
          go get github.com/golang/protobuf/proto
          go get v2ray.com/core/app/router

      - name: Run main.go
        run: |
          cd mymodule
          go run main.go

      - name: List directory contents
        run: |
          echo "Listing contents of the directory:"
          ls -la  # 查看根目录内容，确保文件已生成
